name: atlas-commerce

services:

  postgres:

    image: postgres:17

    container_name: atlas-postgres

    restart: unless-stopped

    environment:

      POSTGRES_DB: atlas_commerce

      POSTGRES_USER: atlasADMIN

      POSTGRES_PASSWORD: atlas123ADM

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

    networks:

      - atlas-network

volumes:

  postgres_data:

networks:

  atlas-network: